Do test and API function for list of md.
trueklimandr/proj1_MD pull request #1
Opened 2018-03-01 06:01 UTC by trueklimandr

2018-03-01 07:29 UTC, abelharisov requested changes

2018-03-01 07:29 UTC, abelharisov commented on composer.lock
> +    "content-hash": "656ea16b1def187e874ab542ab0ba4fe",
Посмотри зачем этот файл(composer.lock) вообще нужен, за что он отвечает, когда его нужно комитить, а когда нет. Это надо знать и это могут спросить на собесе

2018-03-01 07:29 UTC, abelharisov commented on composer.json
> +        "yiisoft/yii2-swiftmailer": "~2.0.0",
Еще посмотри какие есть способы указания версий
https://getcomposer.org/doc/articles/versions.md#versions-and-constraints

2018-03-01 07:29 UTC, abelharisov commented on config/test.php
> +);
Добавь в конец пустую строку
Обычно принято, что бы в конце файла всегда была пустая строка

2018-03-01 07:29 UTC, abelharisov commented on config/test_db.php
> +$db['dsn'] = 'mysql:host=localhost;dbname=medic_tests';
хранить разные параметры вроде паролей к бд или к другим вещам нежелательно, так как обычно разработчикам они не нужены и не стоит ими разбрасываться)
для этого делают отдельный конфиг(test_db_local.php), который добавляется в .gitignore и потом в index.php он объединяется с основным конфигом.
например:
```
$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/../../common/config/main.php'),
    require(__DIR__ . '/../../common/config/main-local.php'),
    require(__DIR__ . '/../config/main.php'),
    require(__DIR__ . '/../config/main-local.php')
);
```

2018-03-01 07:29 UTC, abelharisov commented on config/web.php
> +                'class' => 'yii\rest\UrlRule', 'controller' => 'doctors'
в две отдельные строки разбей

2018-03-01 07:29 UTC, abelharisov commented on controllers/DoctorsController.php
> +class DoctorsController extends ActiveController
Обычно контролеры именуются в единственном числе от имени модели, т.е. DoctorController

2018-03-01 07:29 UTC, abelharisov commented on controllers/DoctorsController.php
> +    public $modelClass = 'app\models\Doctors';
Doctor::class

2018-03-01 07:29 UTC, abelharisov commented on migrations/m180227_123943_create_doctors_table.php
> +            'firstname' => $this->string(255),
Для именования полей обычно используют разные стили: firstName, FirstName, first_name и т.д. Главное что бы отедьные слова в названии были как-то отделены. Как конкретно зависит от проекта и принятого стиля. У нас давай назовем firstName

2018-03-01 07:29 UTC, abelharisov commented on models/Doctors.php
> +class Doctors extends ActiveRecord
Модель у нас обозначает одного врача - Doctor

2018-03-01 07:29 UTC, abelharisov commented on tests/functional/ListOfDocsCest.php
> +class ListOfDocsCest
Давай лучше назовем DoctorIndexActionCest
Doctor - контроллер
IndexAction - action который тестируем

2018-03-01 07:29 UTC, abelharisov commented on tests/functional/ListOfDocsCest.php
> +    public function getListOfZeroDocs(\FunctionalTester $I)
обычно тестовые методы называют `testSomething` функциональные тесты в codeception можно называть как угодно, но если писать unit тесты или использовать phpUnit то они всегда должны начинаться с test

2018-03-01 07:29 UTC, abelharisov commented on tests/functional/ListOfDocsCest.php
> +        $I->haveMultiple(Doctors::class, 0);
Нет смысла это писать)

2018-03-01 07:29 UTC, abelharisov commented on models/Doctors.php
> +class Doctors extends ActiveRecord
И в бд тоже надо поменять название таблицы
https://stackoverflow.com/a/5841297/2367294

2018-03-01 07:29 UTC, abelharisov commented on migrations/m180227_123943_create_doctors_table.php
> +            'spec' => $this->string(255),
пиши названия полностью, не всегда может быть ясно какого слова это сокращение

2018-03-01 07:34 UTC, trueklimandr commented on tests/functional/ListOfDocsCest.php
> +        $I->haveMultiple(Doctors::class, 0);
А если таблица уже не пустая?

2018-03-01 08:19 UTC, abelharisov commented on tests/functional/ListOfDocsCest.php
> +        $I->haveMultiple(Doctors::class, 0);
ничего страшного
делают так:
* если таблица уже есть на проде и ее нужно переименовать, делают отдельную миграцию для этого
* если таблица только у тебя на компьютере есть, то просто сначала откати эту миграцию(кажется команда `yii migrate/down 1`), а потом препеисывай и заново применяй. ну или можно вообще пересоздать бд заново

2018-03-01 08:21 UTC, abelharisov commented on models/Doctors.php
> +class Doctors extends ActiveRecord
И еще посмотри про phpDoc https://docs.phpdoc.org/references/phpdoc/tags/property.html
Это штука позовляет документирвоать код на php
Здесь, например, стоит добавить аннотацию @property для полей модели. Тогда phpStorm будет их читать и подставлять поля при автодополнении

2018-03-01 14:56 UTC, abelharisov requested changes
ты пропустил одно замечание с названиями полей)

2018-03-01 14:56 UTC, abelharisov commented on config/.gitignore
> +*local.php
вообще во всех файлах проверяй пустую строку в конце. у нас на проекте это всегда замечают и просят исправить) тут даже гит хаб это подсвечивает

2018-03-01 14:56 UTC, abelharisov commented on controllers/DoctorController.php
> +    public $modelClass = 'app\models\Doctor';
Doctor::class
Стоит использовать всегда такой способ получения олного имени класса
Например, если Doctor будет перемещен в другой namespace, то эту строку тоже нужно будет обновить, но это очень легко можно забыть сделать, или вообще не знать что где-то есть такой строковое имя класса
Если использовать Doctor::class, то здесь ничего не надо будет менять, кроме импортов класса, а там IDE сразу покажет, что импорт указан не верно

2018-03-01 14:56 UTC, abelharisov commented on migrations/m180227_123943_create_doctors_table.php
> +            'firstname' => $this->string(255),
давай использовать здесь lowerCamelCase для именований полей. соотвественно аннотации @property тоже надо будет обновить
еще потом почитай про code style
в проектах на php обычно используют https://www.php-fig.org/psr/psr-2/

2018-03-02 06:01 UTC, abelharisov approved these changes

2018-03-02 06:20 UTC, merged